# Generated by Django 4.2.8 on 2025-12-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
