# Generated by Django 4.2.8 on 2025-12-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='use_ai_classification',
            field=models.BooleanField(default=True),
        ),
    ]
