# Generated by Django 4.2.8 on 2025-12-24 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_use_ai_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='use_ai_classification',
        ),
    ]
