# Generated by Django 4.2.8 on 2025-12-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userprofile_use_ai_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
