# Generated by Django 4.2.8 on 2025-12-22 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('books', 'Books'), ('jewelry', 'Jewelry'), ('documents', 'Documents'), ('keys', 'Keys'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('location', models.CharField(max_length=300)),
                ('ai_tags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed')], default='found', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('contact_revealed', models.BooleanField(default=False)),
                ('claimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to='items.claim')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='items_notif_recipie_980a7d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user', 'created_at'], name='items_item_user_id_0c5d74_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['status', 'category'], name='items_item_status_c006b3_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['item', 'claimed_at'], name='items_claim_item_id_314e39_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claimer', 'claimed_at'], name='items_claim_claimer_3badf2_idx'),
        ),
    ]
