# Generated by Django 4.2.8 on 2025-12-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_claim_accepted_at_claim_rejected_at_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
