# Generated by Django 4.2.8 on 2025-12-23 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='items.claim'),
        ),
    ]
